Ch3d2 auto
payfunc/cli-card pull request #48
Opened 2021-01-28 16:17 UTC by robinnedergard

2021-01-28 16:41 UTC, florianebmeier requested changes

2021-01-28 16:41 UTC, florianebmeier commented on Verification/Challenge/get.ts
> +	let challengeData = authly.Base64.encode(
Don't reuse variables

2021-01-28 16:41 UTC, florianebmeier commented on Verification/Challenge/get.ts
> +	const challengeNotificationUrl =
Keep variable close to where it is used. Only use is in line 50

2021-01-28 16:41 UTC, florianebmeier commented on Verification/Challenge/get.ts
> +			const merchant = (await authly.Verifier.create("public").verify(
Bump authly.

2021-01-28 16:41 UTC, florianebmeier commented on Verification/Method/get.ts
> +	let methodData = authly.Base64.encode(
Dont reuse variables

2021-01-28 16:46 UTC, florianebmeier approved these changes

2021-01-29 13:35 UTC, fredrikbryntesson approved these changes

2021-01-29 13:35 UTC, merged